apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec: 
  replicas: 3
  selector:
    matchLabels:
      componet: web
  template:
    metadata:
      labels:
        componet: web
    spec:
      containers:
        - name: client
          image: svvone/multi-client:v1
          ports:
            - containerPort: 3000